### ISSUE TITLE
Anchor in HD timeline

### ISSUE THREAD

**Issue by PixRob** [forrestkirby/herzogdupont-joomla#11]
(01) Using TinyMCE with Herzog HD Timeline to put an anchor in an item, **_it does not save input._**
https://schelpen.freesite.host/index.php/timeline

 - OS [e.g. iOS, Windows 10]
 - Browser chrome, 
 - YOOtheme Pro Version [yootheme_j3_2.6.7]
 - Herzog Dupont for YOOtheme Pro Version [e.g. 1.0.0]
 - Joomla 3.10.2
 
![2021-10-15_115226 trying to enter anchor](https://user-images.githubusercontent.com/8125161/137470854-7694b231-48b0-448c-939b-aeafd96e268c.jpg)
![2021-10-15_115226 trying to enter anchor 02](https://user-images.githubusercontent.com/8125161/137470856-96f6c5d0-df96-4475-8477-88a9011e6698.jpg)
-

**Comment by PixRob** [comment]
Sorry; Windows 7 is used

**Comment by forrestkirby** [comment]
Hi PixRob,

your screenshot shows that you do not have any content yet in that field. However, you must have at least one character in the content field, else the TinyMCE editor will not allow to add an anchor (or will strip it right away). This behaviour is not specific to the timeline element, you should get the exact same behaviour for other elements like the grid element or even when editing a native Joomla! article without the YOOtheme Pro page builder. I just tested this and could add an anchor to the content field of a timeline element after I had written at least one character into that field.

![](https://fuse.herzog-dupont.de/images/15-10-_2021_13-07-40.jpg)

Kind regards
