### ISSUE TITLE
Timeline issue

### ISSUE THREAD

**Issue by makatsis** [forrestkirby/herzogdupont-joomla#13]
**Describe the bug**
After the last update (version 1.5.1) the vertical line to timeline was disappered. 
<img width="427" alt="Στιγμιότυπο 2021-12-01, 6 25 01 μμ" src="https://user-images.githubusercontent.com/2492623/144274095-9d83e773-3584-4246-ac01-8b620e1ca44e.png">

Thank you

**Comment by forrestkirby** [comment]
Hi makatsis,

Please try to recompile the LESS styles in the Style Customizer. Does that help?

Kind regards

**Comment by makatsis** [comment]
Yes you are right!! 

Thank you!

**Comment by forrestkirby** [comment]
Great, thanks for reporting back. :-) I'll close this issue now.
