### ISSUE TITLE
the image is out of bounds set by the constructor

### ISSUE THREAD

**Issue by AlixanTelnov** [forrestkirby/herzogdupont-joomla#14]
Rarely, but sometimes it happens, the layout of the element is dispersed. It was on this site that I began to notice this more often. But before that, I had met this several times and it disappeared by itself.

**To Reproduce**
In video

https://mkdental.ge/administrator/index.php?option=com_ajax&templateStyle=9&p=customizer&format=html&site=https%3A%2F%2Fmkdental.ge%2Fka%2Fdental-clinic%2Ftreatment-and-prevention-of-dental-diseases%2Fcaries-treatment

2. Select images in HD IMAGE COMPARISON '....'
3. Scroll down to Examples before and after treatment
![2021-12-15_16-09-34](https://user-images.githubusercontent.com/77014199/146192924-47467f2a-cbcc-4d8c-b1f9-11710097ead7.png)

4. See other elements will be resized

**Client (please complete the following information):**
 - Windows 10
 - Browser chrome 96.0.4664.110
 - YOOtheme Pro Version 2.7.4
 - Herzog Dupont for YOOtheme Pro Version 1.5.3

https://user-images.githubusercontent.com/77014199/146195083-8cb30722-0d01-458e-9654-017d9048915a.mp4

**Comment by forrestkirby** [comment]
Hi AlixanTelnov,

thanks for reporting, I could see the issue on your site and will try to reproduce it on my end for further investigation. Please note that this is a public repository, so you should not share any access data here.

Kind regards

**Comment by AlixanTelnov** [comment]
Thank you for your responsiveness, can you save this data and remove it from public access?   -- С уважением,Аликсан Тельновhttps://dental-site.ruhttps://alimpica.ru 8-905-220-3610vk.com/telnoff   15.12.2021, 17:12, "forrestkirby" ***@***.***>: Hi AlixanTelnov,thanks for reporting, I could see the issue on your site and will try to reproduce it on my end for further investigation. Please note that this is a public repository, so you should not share any access data here.Kind regards—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlixanTelnov** [comment]
Thanks for your modules and additions. Please tell me if version 1.6 will correct the situation that was observed on my site?

**Comment by forrestkirby** [comment]
Hi,

no, 1.6 only added support for a new setting. The image comparison element is not fixed yet. I will provide you with an update once it is.

Best regards

**Comment by forrestkirby** [comment]
Thank you for your patience. I have applied a patch to your website. Could you please check whether the initialization of the image comparison element is now more constant (i. e. whether the images are properly sized once the page is fully loaded)?

If you want to restore the previous state, simply reinstall the plugin.

Thank you

**Comment by AlixanTelnov** [comment]
Great, now the module works stably on this site.
Yesterday I filled the site of another clinic and saw the same difficulties on it, can we apply these fixes on it?

https://vashdoctord.ru/administrator/index.php?option=com_ajax&templateStyle=9&p=customizer&format=html&site=https%3A%2F%2Fvashdoctord.ru%2Flechenie-kariesa%2Fotbelivanie-zubov

login&password - herzogdupont

**Comment by forrestkirby** [comment]
You can simply copy the file `/plugins/system/herzogdupont/modules/elements/elements/hd-image-comparison/js/hd-image-comparison.js` from the page with the patch to your PC/Mac via FTP, then upload it to the other page replacing the file with the same name.

**Comment by forrestkirby** [comment]
Hi again,

this issue should be fixed with [this commit](https://github.com/forrestkirby/herzogdupont-joomla/commit/7c18f0252b69d128b9aa43530f0f269a79f9ffcc). Version 1.6.1 has been released today. Please apply the update.

As you confirmed that the patch is working on your end, I’ll close this issue.

Thanks for reporting!

Best regards
Thomas
