### ISSUE TITLE
Upgrade Process from Standalone Element to Plugin

### ISSUE THREAD

**Issue by ibweb** [forrestkirby/herzogdupont-joomla#20]
Before you created the plugin for managing your elements, we had to manually install the elements that we wanted to use.
What is the correct upgrade process for a site that already has some of your elements manually installed (e.g. Timeline, flipcard, etc.) if we want to convert to using your plugin to manage the elements?
We simply tried a test of installing the plugin on a site that already had the Timeline element...it didn't go well :)

**Comment by forrestkirby** [comment]
H ibweb,

assuming you are using the latest version of the timeline element (via child theme), please try to take the following steps

1. take a backup of your website
2. install the plugin
3. [recompile the style](https://yootheme.com/support/yootheme-pro/joomla/style-customizer#recompile-style)
4. delete the folders `hd-timeline` and `hd-timeline_item` from the child theme directory

**Comment by forrestkirby** [comment]
closed due to inactivity

**Comment by ibweb** [comment]
@forrestkirby, thank you.  We've successfully tested this upgrade process on one site and will roll it out to several more in the coming weeks.
