### ISSUE TITLE
How to contribute to documentation?

### ISSUE THREAD

**Issue by rvalitov** [forrestkirby/herzogdupont-joomla#23]
Hi!
Is documentation at https://herzog-dupont.de/documentation/herzog-dupont-for-yootheme-pro Github based? Is there a way to make pull requests there?

**Comment by forrestkirby** [comment]
Hi rvalitov,

thanks for contributing! No, the documentation is not on GitHub, only the plugin is. If this was needed I would consider putting it on GitHub, but up to now I was the only one working on the docs. For now, if you have something to add/correct, you can post it here as an issue or send it to me via e-mail (see the legal notice on the plugin website).

Best regards

**Comment by rvalitov** [comment]
Thank you! I think info about the #24 should be added to the docs.

**Comment by forrestkirby** [comment]
I have added the entry *Animation Name* to the list of settings for the lottie element. If you think something else is missing, please let me know. Thank you.
