### ISSUE TITLE
Canvas is not resized when browser window is resized at HD Lottie

### ISSUE THREAD

**Issue by rvalitov** [forrestkirby/herzogdupont-joomla#25]
If Canvas renderer is used at HD Lottie and the browser window is resized, then the canvas is not resized. As a result it may lead to pixelization and pour rendering quality because of resolution mismatch. Listening to window resize event and changing the canvas size should solve this issue.

**Comment by forrestkirby** [comment]
Hi rvalitov,

thanks for reporting! This should be fixed with the referenced commit. If the issue persists, pelase re-open the issue. Thank you.

Best regards
