### ISSUE TITLE
Gallery of photo comparaison

### ISSUE THREAD

**Issue by serge-sd** [forrestkirby/herzogdupont-joomla#33]
Hello
Is it possible to do a gallery of  image comparaison ?

I develop a site for a photographs'club.

And I have to create gallery name Before/After when photographer post a post one out of the camera and one after photo processing

But in one evening we have more than twenty couple of photos that I then want to put in comparison on our site

And I use Essential of Zoolanders to import my gallery from a CSV

Thank you for help

**Comment by forrestkirby** [comment]
Hi serge-sd,

the image comparison element is a basic element, what you need is a multiple items element. To achieve this, you would need to create a new, separate element which has some kind of grid layout and the code for the items (children) of this element could mainly be copied from the image comparison.

As a workaround you could try the following:

- Add an image comparison element
- Choose the dynamic content and set *Start* (in the advanced tab) to `1` (default)
- Map the fields as needed
- Copy the first element and set *Start* to `2`
- Copy the first or second element and set *Start* to `3`
- Continue to copy the element until you have reached the maximum number of element you can have
- If you have less images than the number of element, they should not be filled with images and, thus, collapse

Kind regards

**Comment by serge-sd** [comment]
Hello
No possible to be one of your add on ?

Best regards
Serge

Le lun. 12 sept. 2022, 20:14, forrestkirby ***@***.***> a
écrit :

**Comment by forrestkirby** [comment]
It would be possible, but I have no plans to do so at the moment.
