### ISSUE TITLE
Issue with more than 3 icon links in Contnet on the back card

### ISSUE THREAD

**Issue by mamboklaus** [forrestkirby/herzogdupont-joomla#47]
`Hi,`
 
We worked very well with YTP and your great plugin flipcard. The project can be seen here:
https://derbergruht.de/#partner
All works fine.
One strange Issue:
I need to add some, up to 5 links on the back of the flip Cards.
I managed it with html code added in the content.
Works everywhere.. in chrome/FF/Opera – only in Safari and in all Mobile Browser:
only the two last icons are working as expected all others on the left of this two last does not work.
AND I have no Idea what it is.
If I add this html code in a ‘normal’ content, it works – so I suspect that there is something with the flipCards?
Do you have any idea?

Thanks
Klaus
Issue is on:
Joomal 4 and WP
YTP = Current Version
PHP = 8.n
Issue only on Safari & Mobile Browsers
Here is the code I need to add:

`<span style="bottom: 5px; text-align: center;">
<a href="https://www.facebook.com/bergkirchweih" target="_blank" uk-icon="icon:facebook;" rel="noopener"></a><a href="https://www.tiktok.com/@bergkirchweih" target="_blank" uk-icon="icon:tiktok;" rel="noopener"></a><a href="https://www.instagram.com/erlangerbergkirchweih/" target="_blank" uk-icon="icon:instagram;" rel="noopener"></a><a href="https://www.youtube.com/@erlangerbergkirchweih" target="_blank" uk-icon="icon:youtube;" rel="noopener"></a></span>`

**Comment by forrestkirby** [comment]
Hi,

I could not reproduce this issue, neither on a mobile phone nor on MacOS/Safari. https://app.screencast.com/yTVw5cVKpPsNb 

Best regards
