### ISSUE TITLE
click counter

### ISSUE THREAD

**Issue by blondie63** [forrestkirby/herzogdupont-joomla#5]
Hi, using TOGGLE COMPONENT, is there a way to count and save the user clicks ?
Only for statistics.. :)

**Comment by forrestkirby** [comment]
Hi blondie63,

there is no such feature integrated. You could add your own event listener to the button via custom JavaScript or by editing hte `button` in [`/modules/elements/elements/hd-toggle/templates/template.php`](https://github.com/forrestkirby/herzogdupont-joomla/blob/main/modules/elements/elements/hd-toggle/templates/template.php)
