### ISSUE TITLE
Toggle Element - Change Label To "Read Less" and Location When Toggled?

### ISSUE THREAD

**Issue by MarkAm3** [forrestkirby/herzogdupont-joomla#50]
I'm using the Toggle element on my YooTheme joomla website to add a "Read More" button on my website.  So once the button is toggled the remaining text of the webpage appears after the intro text.  I'm not a coder or developer, just setting up my own website, and this plugin is a lifesaver.

Just wondering how I could get the label of the button to change (from "read more" to "read less") after it is toggled and how to get the button to move to below the "content 2" text once it is toggled.

I was hoping to find this in the documentation but did not see it anywhere.

**Comment by forrestkirby** [comment]
Hi MarkAm3,

please hcek ou thte Demo 2 on [this page](https://herzog-dupont.de/yootheme-pro/toggle-element). Is this what you are looking for? If so, I recommend to simply download the demo layout from that page and import it into your layout. Then you can easily check the settings or just re-use the demo and delete anything you don’t need. See [Download and Upload Layouts](https://yootheme.com/support/yootheme-pro/joomla/layout-library#download-and-upload-layouts) for details on how to import a layout.

Best regards

**Comment by MarkAm3** [comment]
Hi,

 Thanks for getting back so soon.  I loaded the template and have
replicated the settings and have been able to get the buttons to work as
they do in the demo..  Thanks so much again!
--Mark

**Comment by MarkAm3** [comment]
Just one more question on the demo 2  layout and settings that essentially provides read more and read less buttons with expanded text.  With the current settings when you toggle the read less button it hides the "read less" button and the text in the "read less" content field.  But if there is a lot of text in the content field that is now hidden when you click on the "read less" button you are left at the bottom of the web page.  Is there a setting for the read less button that returns the view to the top of the page-in other words back to the top of the web page showing the intro text and the "read more" button?

**Comment by forrestkirby** [comment]
No, there no such setting. But you can achieve this with a custom script. Assume your second toggle element has the ID `toggle-2`, the following should cause the website to scroll to the top after the text has been hidden.

```js
<script>
UIkit.util.ready(_=>{
    UIkit.util.on('#toggle-2', 'hidden', _ => {
         window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
    });
});
</script>
```

[example layout](https://yootheme.herzog-dupont.de/downloads/layouts/toggle-element-demo-scrolltotop-issue-50.json)

Best regards

**Comment by MarkAm3** [comment]
Fantastic!  That did it!

Thanks again!

--Mark
