### ISSUE TITLE
herzog dupont element HD-timline doesnt work in my template 

### ISSUE THREAD

**Issue by himmlischd** [forrestkirby/herzogdupont-joomla#52]
**Describe the bug**
the Hd Timeline doesn't work. It shows only one line. (Yootheme pro 4.0, Joomla 4.xx PHP 8.1.)

**To Reproduce**
1. Go to https://check-relaunch.de/
3. Click on: startpage
4. Scroll down to "Titel Timleine doesnt work"
5. See error: the content is not left / right . the line in the middle is missing. 

**Expected behavior**
what can I do to get a working timeline?

**Screenshots**

**Client (please complete the following information):**
 - OS [e.g. iOS, Windows 10]
 - YOOtheme Pro Version 4.0.10
 - Herzog Dupont for YOOtheme Pro Version 4.0.10, jommla 4.xx

**Additional context**

Would be happy if someone helps me best regards,

**Comment by forrestkirby** [comment]
Hi,

can you please recompile the style in the style customizer? Does that help?

Best regards

**Comment by forrestkirby** [comment]
Good to read that it's working now, thanks for reporting back!
