### ISSUE TITLE
Counter elements counting before in viewport

### ISSUE THREAD

**Issue by CheeseyScone** [forrestkirby/herzogdupont-joomla#55]
Since Yootheme 4.2.1 upgrade, the counter elements on my sites count immediately on page load only. They don't wait until element is in viewport.

Happens with Herzog Dupont for YOOtheme Pro version 1.7.1 and 1.7.2
Am on Joomla 4.4.0

**Comment by forrestkirby** [comment]
Hi CheeseyScone,

thanks for reporting. Please try to replace

```js
if (!el.getAttribute('data-animated') && ((typeof UIkit.util.isInView === 'function' && UIkit.util.isInView(el)) || (typeof UIkit.util.isVisible === 'function' && UIkit.util.isVisible(el)))) {
```

```js
if (!el.getAttribute('data-animated') && UIkit.util.isInView(el)) {
```
 in `plugins/system/herzogdupont/modules/elements/elements/hd-counter/js/hd-counter.js`.

Kind regards
Thomas

**Comment by CheeseyScone** [comment]
Thanks very much. That has now rectified the issue.

**Comment by forrestkirby** [comment]
will be fixed with https://github.com/forrestkirby/herzogdupont-joomla/commit/91105e2cf7af4e007a7acbdc5be21a6f7b4597c4
