### ISSUE TITLE
After installing herzogdupont-joomla-1.8.0.zip installed version doesn't change (still 1.7.2)

### ISSUE THREAD

**Issue by formfranska** [forrestkirby/herzogdupont-joomla#57]
Hi Thomas, I hope this isn't some error on my part but I already had v 1.7.2 installed. **New version 1.8.0** was not found by extension updater so installed it manually (twice). 
Under System > Manage > Extensions, it still says  	Plugin 	1.7.2 	2023-11-01.

I looked in the xml file and saw that it still says:  <version>1.7.2</version> Is this what's causing it? I'm just a graphic designer so just guessing 😅

**Comment by forrestkirby** [comment]
Hi,

that was a mistake on my end. I inadvertently numbered the release 1.7.2 whereas it should’ve been 1.8.0. It’s corrected now on the update server, you can get it directly from [there](https://yootheme.herzog-dupont.de/releases/herzogdupont-joomla-1.8.0.zip). Simply upload & install. Thanks for reporting!

Best regards

**Comment by formfranska** [comment]
Thanks 🙏🏽👍🏽
