### ISSUE TITLE
HD Timeline - issue with CSS?

### ISSUE THREAD

**Issue by Sulpher** [forrestkirby/herzogdupont-joomla#66]
Hello,
I've installed the version 1.8.0 of the package which consists of various elements including HD Timeline.

I see an issue with CSS:
<img width="2012" alt="Снимок экрана 2024-07-02 в 17 40 01" src="https://github.com/forrestkirby/herzogdupont-joomla/assets/3432048/7750deaa-6f87-4eb0-91c3-f7cf50484cf6">

There is no left / right design as it is expected.
And I have another site with an old element which works correctly:
<img width="1358" alt="Снимок экрана 2024-07-02 в 17 42 51" src="https://github.com/forrestkirby/herzogdupont-joomla/assets/3432048/b3dd07cc-5d05-472f-b4b1-a983cec5a073">

I suppose something need to be fixed in the current version of HD Timeline element.  
Thanks.

**Comment by forrestkirby** [comment]
Please recompile the style. See https://yootheme.com/support/yootheme-pro/joomla/style-customizer#recompile-style for instructions.

**Comment by Sulpher** [comment]
I did not know about that.  Thanks a lot.
