### ISSUE TITLE
The Flipcart Elements are bugging

### ISSUE THREAD

**Issue by str8up-support** [forrestkirby/herzogdupont-joomla#8]
When you click on one Flipcard Element and hover after that above another, both Card Elements will flipp.

**To Reproduce**
1. Click on one Flipcard Element.
2. Hover above another.
3. Both Elements will flipp.

**Expected behavior**
Not both Elements should flipp, only the one you are hovering on.

**Client (please complete the following information):**
 - all devices and Systems
 - all Browsers
 - YOOtheme Pro Version (2.5.9)
 - Herzog Dupont for YOOtheme Pro Version (1.3.1)

**Comment by forrestkirby** [comment]
Hi str8up-support,

I could not reproduce the behaviour you described. Hovering one flip card should not cause another to flip. Losing the hover state might cause a flip card to flip if you have chosen `hover` or `hover, click` as flip mode. This is intended.

Is there a website I can inspect to reproduce this behaviour? Which flip mode are you using?

Kind regards

**Comment by forrestkirby** [comment]
closed due to inactivity
